all:put.o rustsbi.o rand.o string.o

put.o:
	$(GCC) $(CFLAG) -c put.c -o ../build/put.o

rustsbi.o:
	$(GCC) $(CFLAG) -c rustsbi.c -o ../build/rustsbi.o

rand.o:
	$(GCC) $(CFLAG) -c rand.c -o ../build/rand.o

string.o:
	$(GCC) $(CFLAG) -c string.c -o ../build/string.o